### ISSUE TITLE
Suggestion. Limit DDNS to named domains, subdomains

### ISSUE THREAD

**Issue by plutocrat** [porkbundomains/porkbun-dynamic-dns-python#7]
Hi, 
I've always shied away from using API based DDNS updaters such as this one, and Cloudflares, as the API key has access to the entire account, and as such is a security risk. If an API key were to be limited to a single domain within the account, or, even better, if you could activate it on a single subdomain, that would make it a lot more attractive.

**Comment by rossporkbun** [comment]
That's a great bit of feedback and I'll make sure our API developer sees this request, but it's outside the scope of the client, so I'm closing for now.
