### ISSUE TITLE
Different DNS record types

### ISSUE THREAD

**Issue by cl0rm** [porkbundomains/porkbun-dynamic-dns-python#8]
Currently, this Python version does not support setting the record Type (for example MX record). The java version (https://github.com/porkbundomains/porkbun-dynamic-dns-java) does seem to do so.

**Comment by rossporkbun** [comment]
Hi, thanks for this request. MX records can't have IP address answers. The MX record should have an A record for an answer. That A record can be set via the client, I think that's what you want to do here.
